# SpinApp per il componente WASM Aggregator
# L'applicazione riceve gli aggiornamenti dai sensori (via MQTT)
# e aggiorna le CRD ParkingLot e ParkingSpace nel cluster Kubernetes.
apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: smart-parking-aggregator               # Nome della SpinApp
  namespace: smart-parking                     # Namespace dedicato all'app Smart Parking
spec:
  image: ghcr.io/antoninovenuto95/smart-parking-aggregator:0.1.1   # Immagine del WASM aggregator pubblicata su GitHub Container Registry
  executor: containerd-shim-spin               # Runtime usato per eseguire le app Spin (SpinKube)
  replicas: 1                                  # Numero di repliche del pod
  serviceAccountName: spinkube-aggregator      # ServiceAccount con i permessi RBAC definiti nel file precedente
  variables:
    # Configurazione MQTT: broker e topic da sottoscrivere
    - name: broker_addr
      value: "mqtt://mosquitto.smart-parking.svc.cluster.local:1883"  # Indirizzo interno del broker MQTT
    - name: topic
      value: "parking/+/+/status"              # Topic MQTT con wildcard per ricevere tutti gli aggiornamenti di stato
    
    # Configurazione per interagire con le CRD nel cluster
    - name: namespace
      value: "smart-parking"                   # Namespace in cui operano le CRD
    - name: group
      value: "parking.smart"                   # API Group delle CRD ParkingLot/ParkingSpace
    - name: version
      value: "v1alpha1"                        # Versione dell’API personalizzata

    # Parametri di connessione al proxy dell’API server
    - name: k8s_scheme
      value: "http"                            # Protocollo usato per comunicare con l’API server (via proxy)
    - name: k8s_host
      value: "kubeapi-proxy.smart-parking.svc" # Service interno che fa da proxy al kube-apiserver
    - name: k8s_port
      value: "8000"                            # Porta esposta dal proxy

    # Token di autenticazione per l’accesso all’API server
    # Estratto da un Secret Kubernetes
    - name: k8s_token
      valueFrom:
        secretKeyRef:
          name: k8s-token-secret               # Nome del Secret contenente il token
          key: k8s_token                       # Chiave del Secret da usare
          optional: false                      # Il token è obbligatorio per l’avvio dell’app
